### ISSUE TITLE
New SuiteName sometimes takes incredibly long and uses a lot of memory

### ISSUE THREAD

**Issue by russell-taylor** [ReliaSolve/cctbx_project#110]
When run on a PDB or CIF file, sometimes the new code runs for over 31 hours and takes over 8GB of memory.

Files tested and shown to run for more than three minutes:
4v2s.cif
5bzu.cif

Leftover tmp files:
5imr
6cbd
4v2s
5bzu
5zw4
5wqe
4z4i
5awh
6awd
1mzp
6hhq

Zero-sized output files:
2hvy.pdb 2hvy.cif
4v2s.pdb 4v2s.cif
5bzu.cif
5zw4.pdb
3k1v.pdb
4z4i.cif
3mut.cif
5js2.cif
6dp4.cif
6dpb.cif
5wqe.cif

**Comment by russell-taylor** [comment]
4v2s.cif was still running after an hour, so it is definitely one that can be used to debug this.

**Comment by Joymaker** [comment]
Here's what's going on: 4v2s contains the following very broken residue, which interrupts the backbone chain: it was causing my dihedral angle algorithm to get into a loop, which for some strange reason was near-infinite instead of infinite.

ATOM   3502  P     C Q  19     -52.004  -7.294  -4.598  1.00198.62           P
ATOM   3503  OP1   C Q  19     -53.416  -7.128  -5.026  1.00204.58           O
ATOM   3504  OP2   C Q  19     -51.110  -8.207  -5.355  1.00182.23           O
ATOM   3505  O5'   C Q  19     -51.309  -5.861  -4.513  1.00193.03           O
ATOM   3506  P     C Q  22     -43.059  -5.469 -13.145  1.00217.66           P

To get past this, I will need to either bail out with a message to standard error, or teach my algorithm to do something it doesn't know how to do, taking probably an hour or so of my time. Given how we are with time at the moment, I'm bailing out. Let me know if you would like the other answer.

**Comment by russell-taylor** [comment]
I think this is the last of the SuiteName issues.  It is worth an hour or so of your time.

**Comment by Joymaker** [comment]
Revised the dihedral angle algorithm to plow forward in cases that were putting it into a (nearly) infinite loop. The new, even more fault-tolerant algorithm occasionally produces an extra suite at the end of the list, which is invariably incomplete.

This cleans up all the files I have tried it on, except 2hvy.

N.B. 2bh2, which has several triages from the dangle version that turn into normal suites via the PDB dihedral angle algorithm.

**Comment by Joymaker** [comment]
Good time for a retest for long-running files. I know of no more infinite loop cases.

**Comment by russell-taylor** [comment]
Lookin' good so far.  31,000 files tested.
