### ISSUE TITLE
See if command-line arguments can be organized in -help without nesting them in Phil

### ISSUE THREAD

**Issue by russell-taylor** [ReliaSolve/cctbx_project#56]
Being able to specify the order is a big part of this
Section headers embedded would be cool too (input flags, output flags, ...)

**Comment by Joymaker** [comment]
Under Phil, command line arguments can be nested into groups. These do not influence how they are accessed on the command line, but it does influence how they are accessed in the program code: an extra level of qualification is needed on the name of the parameter.
    options.suitename.output.kinemage
instead of
    options.suitename.kinemage

So in answer to the Richardson's question, I don't think grouping them creates any prohibitive difficulty.

**Comment by russell-taylor** [comment]
So how does Phil know that the command-line argument 'kinemage=True' should map into the variable options.suitename.output.kinemage rather than some other name like options.kinemage or options.otherlibrary.kinemage?

**Comment by Joymaker** [comment]
The answer? I get an error, and not a very informative one, if the duplication you described exists. Phil's argparse raises Sorry without a truly relevant explanation.

Ken
On 4/26/2021 8:59:15 PM, Russell Taylor ***@***.***> wrote:
So how does Phil know that the command-line argument 'kinemage=True' should map into the variable options.suitename.output.kinemage rather than some other name like options.kinemage or options.otherlibrary.kinemage?

**Comment by russell-taylor** [comment]
Okay, so to work in the general case they do need to be fully specified.  This would not be such a problem when they are run by scripts but would be a pain when they were run by hand.  But when they are run by hand the user can compensate if they fail, but only if they know what went wrong. :-)
